name: cybear_jinni
description: CyBear Jinni app to interact with your CyBear Jinni Smart Devices
version: 1.1.0+25
homepage: https://cybearjinni.com
author: Guy Luz

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter_icons:
  ios: true
  android: true
  windows: true
  image_path: "assets/cbj_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/cbj_icon_adaptive.png"

flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true
  assets:
    - assets/
    - assets/symbols/
    - assets/translations/
    - assets/gif/

  fonts:
    - family: gidole_regular
      fonts:
        - asset: assets/gidole_regular.ttf

dependencies:
  # A action bottom sheet that adapts to the platform
  adaptive_action_sheet: ^2.0.0
  # Collection of some cool and awesome text animations.
  animated_text_kit: ^4.2.1
  # More customization when notifying your user.
  another_flushbar: ^1.10.24
  # Declarative routing solution, where everything needed for navigation is automatically generated for you.
  auto_route: ^2.3.0
  # Helps implement the BLoC pattern.
  bloc: ^7.0.0
  # Copy text from and to clipboard
  clipboard: ^0.1.3
#  cloud_firestore: ^2.2.2
  # Allow discover network connectivity
  connectivity_plus: ^1.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.0
  # Get current device information from within the Flutter application.
  device_info: ^2.0.2
  # Internationalization (Easy translations)
  easy_localization: ^3.0.0
  # An "expansion" on the Flutter SDK's standard ExpansionTile
  expansion_tile_card: ^2.0.0
  # Plugin to use the Google Analytics for Firebase API.
#  firebase_analytics: ^8.1.2
#  firebase_auth: ^1.4.1
#  firebase_auth_web: ^1.3.1
#  firebase_core: ^1.3.0
  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^7.1.0
  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^8.1.1+1
  # Getting the local timezone of the os.
  flutter_native_timezone: ^2.0.0
  # An easy to implement custom switch
  flutter_switch: ^0.3.2
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.0.8
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^9.1.0
  # Annotations for freezed
  freezed_annotation: ^0.14.2
  # Service locator
  get_it: ^7.2.0
  # Secure authentication system for signing in with a Google account on Android and iOS
#  google_sign_in: ^5.0.4
  # A high performance, open source, general RPC framework that puts mobile and HTTP/2 first.
  grpc: ^3.0.1
  # Add hex color codes to your flutter projects
  hexcolor: ^2.0.4
  # Lightweight and blazing fast key-value database
  hive: ^2.0.4
  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_flutter: ^1.1.0
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.3
  # Convenient code generator for get_it
  injectable: ^1.4.1
  # Allow you to have a screen at launcher for example
  introduction_screen: ^2.1.0
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.0.1
  # Dart Build System builders for handling JSON.
  json_serializable: ^4.1.3
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^0.9.1
  # Liquid progress indicator for Flutter.
  liquid_progress_indicator_ns: ^1.0.0
  # Handles getting a location on
  location: ^4.3.0
  # Service discovery over multicast DNS (mDNS), Bonjour, and Avahi.
  multicast_dns: ^0.3.0
  # Discover network info and configure themselves accordingly
  network_info_plus: ^1.0.2
  # Finding commonly used locations on the filesystem
  path_provider: ^2.0.2
  # Popup that ask for the requested permission
  permission_handler: ^8.1.4+2
  # Allows to ping IP subnet and discover network devices.
  ping_discover_network_forked: ^0.0.1
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^2.0.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^5.0.0
  # Implementation of the popular reactiveX api for asynchronous programming
  rxdart: ^0.27.1
  # reading and writing simple key-value pairs
  shared_preferences: ^2.0.6
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.4
  # Get available wifi ssid list, user can connect to wifi with ssid and password, and create hotspot
  wifi_iot: ^0.3.4


dev_dependencies:
  # Generator for auto_route library.
  auto_route_generator: ^2.1.0
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # Package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.1
  flutter_test:
    sdk: flutter
  # Code generator for unions/pattern-matching/copy.
  freezed: ^0.14.2
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^1.1.0
  # Convenient code generator for get_it.
  injectable_generator: ^1.4.1
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.5.3
  # Mock framework with APIs for Fakes, Mocks, behavior verification, and stubbing.
  mockito: ^5.0.12