name: cybear_jinni
description: CyBear Jinni app to interact with your CyBear Jinni Smart Devices
version: 1.1.5+45
homepage: https://cybearjinni.com

publish_to: 'none'

environment:
  sdk: ^2.15.0

flutter_icons:
  ios: true
  android: true
  windows: true
  image_path: "assets/cbj_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/cbj_icon_adaptive.png"

flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true
  assets:
    - assets/
    - assets/symbols/
    - assets/translations/
    - assets/gif/

  fonts:
    - family: gidole_regular
      fonts:
        - asset: assets/gidole_regular.ttf

dependencies:
  # A action bottom sheet that adapts to the platform
  adaptive_action_sheet: ^2.0.0
  # Collection of some cool and awesome text animations.
  animated_text_kit: ^4.2.1
  # More customization when notifying your user.
  another_flushbar: ^1.10.28
  # Declarative routing solution, where everything needed for navigation is automatically generated for you.
  auto_route: ^3.2.0
  # Helps implement the BLoC pattern.
  bloc: ^8.0.1
  # Copy text from and to clipboard
  clipboard: ^0.1.3
  # Allow discover network connectivity
  connectivity_plus: ^2.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # Functional programming thingies, let you use multiple return types
  # Functional programming thingipes, let you use multiple return types
  dartz: ^0.10.1
  # Get current device information
  device_info_plus: ^3.1.1
  # Internationalization (Easy translations)
  easy_localization: ^3.0.0
  # An "expansion" on the Flutter SDK's standard ExpansionTile
  expansion_tile_card: ^2.0.0

  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^8.0.0
  # HSV(HSB)/HSL/RGB/Material color picker
  flutter_colorpicker: ^1.0.3
  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^9.1.4
  # Getting the local timezone of the os.
  flutter_native_timezone: ^2.0.0
  # An easy to implement custom switch
  flutter_switch: ^0.3.2
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.0.8
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^9.2.0
  # Annotations for freezed
  freezed_annotation: ^1.1.0
  # Service locator
  get_it: ^7.2.0
  # Secure authentication system for signing in with a Google account on Android and iOS
#  google_sign_in: ^5.0.4
  # A high performance, open source, general RPC framework that puts mobile and HTTP/2 first.
  grpc: ^3.0.2
  # Add hex color codes to your flutter projects
  hexcolor: ^2.0.5
  # Lightweight and blazing fast key-value database
  hive: ^2.0.4
  # Extension for Hive. Makes it easier to use Hive in Flutter apps.
  hive_flutter: ^1.1.0
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.13.4
  # Convenient code generator for get_it
  injectable: ^1.5.0
  # Allow you to have a screen at launcher for example
  introduction_screen: ^2.1.0
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.4.0
  # Dart Build System builders for handling JSON.
  json_serializable: ^6.1.1
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^0.10.0
  # Liquid progress indicator for Flutter.
  liquid_progress_indicator: ^0.4.0
  # Handles getting a location on
  location: ^4.3.0
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # The Material Design Icons designed by the community for Flutter
  material_design_icons_flutter: ^5.0.6595
  # Creating multi-select widgets in a variety of ways
  multi_select_flutter: ^4.0.0
  # Service discovery over multicast DNS (mDNS), Bonjour, and Avahi.
  multicast_dns: ^0.3.1
  # Discover network info and configure themselves accordingly
  network_info_plus: ^2.1.1
  # Querying information about the application package, such as CFBundleVersion
  package_info_plus: ^1.3.0
  # Finding commonly used locations on the filesystem
  path_provider: ^2.0.8
  # Popup that ask for the requested permission
  permission_handler: ^8.3.0
  # Allows to ping IP subnet and discover network devices.
  ping_discover_network_forked: ^0.0.1
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^2.0.1
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.0.1
  # Implementation of the popular reactiveX api for asynchronous programming
  rxdart: ^0.27.3
  # Reading and writing simple key-value pairs
  shared_preferences: ^2.0.11
  # Highly customizable circular slider/progress bar & spinner.
  sleek_circular_slider: ^2.0.1
  # Plugin for launching a URL
  url_launcher: ^6.0.17
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.5
  # Get available wifi ssid list, user can connect to wifi with ssid and password, and create hotspot
  wifi_iot: ^0.3.11


dev_dependencies:
  # Generator for auto_route library.
  auto_route_generator: ^3.2.0
  # A build system for Dart code generation and modular compilation.
  build_runner:

  # Package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  # Code generator for unions/pattern-matching/copy.
  freezed: ^1.1.0
  # Automatically generates TypeAdapters to store any class.
  hive_generator: ^1.1.1
#  # Extension for Hive. Automatically generates TypeAdapters to store any class.
#  hive_generator: ^1.1.0
  # Convenient code generator for get_it.
  injectable_generator: ^1.5.2
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^1.8.1
  # Mock framework with APIs for Fakes, Mocks, behavior verification, and stubbing.
  mockito: ^5.0.12