name: cybear_jinni
description: CyBear Jinni app to interact with your CyBear Jinni Smart Devices
version: 1.4.2+66
homepage: https://cybearjinni.com

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

# Don't get confuse, this is from the package flutter_launcher_icons and not flutter_icons
flutter_icons:
  ios: true
  android: true
  windows: true
  image_path: "assets/cbj_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/cbj_icon_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/symbols/
    - assets/translations/
    - assets/gif/

  fonts:
    - family: gidole_regular
      fonts:
        - asset: assets/gidole_regular.ttf

dependencies:
  # A action bottom sheet that adapts to the platform
  adaptive_action_sheet: ^2.0.2
  # Collection of some cool and awesome text animations.
  animated_text_kit: ^4.2.2
  # More customization when notifying your user.
  another_flushbar: ^1.12.30
  # Utility classes to work with asynchronous computations.
  async: ^2.11.0
  # Declarative routing solution, where everything needed for navigation is automatically generated for you.
  auto_route: ^7.8.4
  # Automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # Helps implement the BLoC pattern.
  bloc: ^8.1.2
  cbj_smart_device_flutter:
    git: https://github.com/CyBear-Jinni/cbj_smart_device_flutter.git
  # Copy text from and to clipboard
  clipboard: ^0.1.3
  # Package to create, convert, alter, and compare colors in a variety of colorspaces.
  color: ^3.0.0
  # Allow discover network connectivity
  connectivity_plus: ^5.0.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.10.1
  # A day night time picker.
  day_night_time_picker: ^1.3.0+1
  # Helps us to select days in a week.
  day_picker: ^2.2.0
  # Get current device information
  device_info_plus: ^9.1.0
  # Internationalization (Easy translations)
  easy_localization: ^3.0.3
  # An "expansion" on the Flutter SDK's standard ExpansionTile
  expansion_tile_card: ^3.0.0
  flutter:
    sdk: flutter
  # Bloc for state management, replace StatefulWidget
  flutter_bloc: ^8.1.3
  # HSV(HSB)/HSL/RGB/Material color picker
  flutter_colorpicker: ^1.0.3
  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^16.1.0
  # An easy to implement custom switch
  flutter_switch: ^0.3.2
  # Getting the local timezone of the os.
  flutter_timezone: ^1.0.8
  # Toast Library for Flutter, Easily create toast messages in single line of code.
  fluttertoast: ^8.2.3
  # Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^10.6.0
  # Annotations for freezed
  freezed_annotation: ^2.4.1
  # Service locator
  get_it: ^7.6.4
  # Google Mobile Ads
  google_mobile_ads: ^3.1.0
  # Secure authentication system for signing in with a Google account on Android and iOS
  #  google_sign_in: ^5.0.4
  # A high performance, open source, general RPC framework that puts mobile and HTTP/2 first.
  grpc: ^3.2.4
  # Add hex color codes to your flutter projects
  hexcolor: ^3.0.1
  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^1.1.0
  # Open source icon sets for flutter
  iconify_flutter: ^0.0.5
  # Convenient code generator for get_it
  injectable: ^2.3.2
  # Allow you to have a screen at launcher for example
  introduction_screen: ^3.1.12
  # Extremely fast, easy to use, and fully async NoSQL database for Flutter.
  isar: ^3.1.0+1
  # Isar Core binaries for the Isar Database. Needs to be included for Flutter apps.
  isar_flutter_libs: ^3.1.0+1
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1
  # Dart Build System builders for handling JSON.
  json_serializable: ^6.7.1
  # Port of Kotlin's Kotlin Standard library for Dart/Flutter projects
  kt_dart: ^1.1.0
  # Liquid progress indicator for Flutter.
  liquid_progress_indicator_v2: ^0.5.0
  # Handles getting a location on
  location: ^5.0.3
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1
  # The Material Design Icons designed by the community for Flutter
  material_design_icons_flutter: ^7.0.7296
  # Creating multi-select widgets in a variety of ways
  multi_select_flutter: ^4.1.3
  # Service discovery over multicast DNS (mDNS), Bonjour, and Avahi.
  multicast_dns: ^0.3.2+4
  # Discover network info and configure themselves accordingly
  network_info_plus: ^4.1.0
  # Helps you discover open ports, devices on subnet and more.
  network_tools: ^4.0.1
  # Querying information about the application package, such as CFBundleVersion
  package_info_plus: ^4.2.0
  # Finding commonly used locations on the filesystem
  path_provider: ^2.1.1
  # Popup that ask for the requested permission
  permission_handler: ^11.0.1
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^3.1.0
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.1.0
  # Implementation of the popular reactiveX api for asynchronous programming
  rxdart: ^0.27.7
  # Reading and writing simple key-value pairs
  shared_preferences: ^2.2.2
  # Highly customizable circular slider/progress bar & spinner.
  sleek_circular_slider: ^2.0.1
  # Plugin for launching a URL
  url_launcher: ^6.2.1
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^4.2.1
  # Get available wifi ssid list, user can connect to wifi with ssid and password, and create hotspot
  wifi_iot: ^0.3.18+1
  # Scan for nearby visible WiFi access points.
  wifi_scan: ^0.4.0+2

dev_dependencies:
  # Generator for auto_route library.
  auto_route_generator: ^7.3.2
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.6
  # Package which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.13.1
  # Code generator for unions/pattern-matching/copy.
  freezed: ^2.4.5
  # Convenient code generator for get_it.
  injectable_generator: ^2.4.1
  # Code generator for the Isar Database. Finds classes annotated with @Collection.
  isar_generator: ^3.1.0+1
  # Collection of lint rules for Dart and Flutter projects.
  lint: ^2.2.0
  #  # Mock framework with APIs for Fakes, Mocks, behavior verification, and stubbing.
  #  mockito: ^5.3.0
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.9
