name: SmartDeviceDart
description: A sample command-line application.
version: 1.0.0
homepage: https://www.example.com
author: guy <email@example.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  firedart: ^0.6.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
